Diagnosis.create!({ idc9: "24900", name:	"Secondary diabetes mellitus without mention of complication, not stated as uncontrolled, or unspecified	 Sec DM wo cmp nt st uncn"})
Diagnosis.create!({ idc9: "24901", name:	"Secondary diabetes mellitus without mention of complication, uncontrolled	 Sec DM wo comp uncontrld"})
Diagnosis.create!({ idc9: "24910", name:	"Secondary diabetes mellitus with ketoacidosis, not stated as uncontrolled, or unspecified	 Sec DM keto nt st uncntr"})
Diagnosis.create!({ idc9: "24911", name:	"Secondary diabetes mellitus with ketoacidosis, uncontrolled	 Sec DM ketoacd uncntrld"})
Diagnosis.create!({ idc9: "24920", name:	"Secondary diabetes mellitus with hyperosmolarity, not stated as uncontrolled, or unspecified	 Sec DM hpros nt st uncnr"})
Diagnosis.create!({ idc9: "24921", name:	"Secondary diabetes mellitus with hyperosmolarity, uncontrolled	 Sec DM hprosmlr uncntrld"})
Diagnosis.create!({ idc9: "24930", name:	"Secondary diabetes mellitus with other coma, not stated as uncontrolled, or unspecified	 Sec DM ot cma nt st uncn"})
Diagnosis.create!({ idc9: "24931", name:	"Secondary diabetes mellitus with other coma, uncontrolled	 Sec DM oth coma uncntrld"})
Diagnosis.create!({ idc9: "24940", name:	"Secondary diabetes mellitus with renal manifestations, not stated as uncontrolled, or unspecified	 Sec DM renl nt st uncntr"})
Diagnosis.create!({ idc9: "24941", name:	"Secondary diabetes mellitus with renal manifestations, uncontrolled	 Sec DM renal uncontrld"})
Diagnosis.create!({ idc9: "24950", name:	"Secondary diabetes mellitus with ophthalmic manifestations, not stated as uncontrolled, or unspecified	 Sec DM ophth nt st uncn"})
Diagnosis.create!({ idc9: "24951", name:	"Secondary diabetes mellitus with ophthalmic manifestations, uncontrolled	 Sec DM ophth uncontrld"})
Diagnosis.create!({ idc9: "24960", name:	"Secondary diabetes mellitus with neurological manifestations, not stated as uncontrolled, or unspecified	 Sec DM neuro nt st uncn"})
Diagnosis.create!({ idc9: "24961", name:	"Secondary diabetes mellitus with neurological manifestations, uncontrolled	 Sec DM neuro uncontrld"})
Diagnosis.create!({ idc9: "24970", name:	"Secondary diabetes mellitus with peripheral circulatory disorders, not stated as uncontrolled, or unspecified	 Sec DM circ nt st uncntr"})
Diagnosis.create!({ idc9: "24971", name:	"Secondary diabetes mellitus with peripheral circulatory disorders, uncontrolled	 Sec DM circ uncontrld"})
Diagnosis.create!({ idc9: "24980", name:	"Secondary diabetes mellitus with other specified manifestations, not stated as uncontrolled, or unspecified	 Sec DM oth nt st uncontr"})
Diagnosis.create!({ idc9: "24981", name:	"Secondary diabetes mellitus with other specified manifestations, uncontrolled	 Sec DM other uncontrld"})
Diagnosis.create!({ idc9: "24990", name:	"Secondary diabetes mellitus with unspecified complication, not stated as uncontrolled, or unspecified	 Sec DM unsp nt st uncon"})
Diagnosis.create!({ idc9: "24991", name:	"Secondary diabetes mellitus with unspecified complication, uncontrolled	 Sec DM unsp uncontrold"})
Diagnosis.create!({ idc9: "25000", name:	"Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled	 DMII wo cmp nt st uncntr"})
Diagnosis.create!({ idc9: "25001", name:	"Diabetes mellitus without mention of complication, type I [juvenile type], not stated as uncontrolled	 DMI wo cmp nt st uncntrl"})
Diagnosis.create!({ idc9: "25002", name:	"Diabetes mellitus without mention of complication, type II or unspecified type, uncontrolled	 DMII wo cmp uncntrld"})
Diagnosis.create!({ idc9: "25003", name:	"Diabetes mellitus without mention of complication, type I [juvenile type], uncontrolled	 DMI wo cmp uncntrld"})
Diagnosis.create!({ idc9: "25010", name:	"Diabetes with ketoacidosis, type II or unspecified type, not stated as uncontrolled	 DMII keto nt st uncntrld"})
Diagnosis.create!({ idc9: "25011", name:	"Diabetes with ketoacidosis, type I [juvenile type], not stated as uncontrolled	 DMI keto nt st uncntrld"})
Diagnosis.create!({ idc9: "25012", name:	"Diabetes with ketoacidosis, type II or unspecified type, uncontrolled	 DMII ketoacd uncontrold"})
Diagnosis.create!({ idc9: "25013", name:	"Diabetes with ketoacidosis, type I [juvenile type], uncontrolled	 DMI ketoacd uncontrold"})
Diagnosis.create!({ idc9: "25020", name:	"Diabetes with hyperosmolarity, type II or unspecified type, not stated as uncontrolled	 DMII hprsm nt st uncntrl"})
Diagnosis.create!({ idc9: "25021", name:	"Diabetes with hyperosmolarity, type I [juvenile type], not stated as uncontrolled	 DMI hprsm nt st uncntrld"})
Diagnosis.create!({ idc9: "25022", name:	"Diabetes with hyperosmolarity, type II or unspecified type, uncontrolled	 DMII hprosmlr uncontrold"})
Diagnosis.create!({ idc9: "25023", name:	"Diabetes with hyperosmolarity, type I [juvenile type], uncontrolled	 DMI hprosmlr uncontrold"})
Diagnosis.create!({ idc9: "25030", name:	"Diabetes with other coma, type II or unspecified type, not stated as uncontrolled	 DMII o cm nt st uncntrld"})
Diagnosis.create!({ idc9: "25031", name:	"Diabetes with other coma, type I [juvenile type], not stated as uncontrolled	 DMI o cm nt st uncntrld"})
Diagnosis.create!({ idc9: "25032", name:	"Diabetes with other coma, type II or unspecified type, uncontrolled	 DMII oth coma uncontrold"})
Diagnosis.create!({ idc9: "25033", name:	"Diabetes with other coma, type I [juvenile type], uncontrolled	 DMI oth coma uncontrold"})
Diagnosis.create!({ idc9: "25040", name:	"Diabetes with renal manifestations, type II or unspecified type, not stated as uncontrolled	 DMII renl nt st uncntrld"})
Diagnosis.create!({ idc9: "25041", name:	"Diabetes with renal manifestations, type I [juvenile type], not stated as uncontrolled	 DMI renl nt st uncntrld"})
Diagnosis.create!({ idc9: "25042", name:	"Diabetes with renal manifestations, type II or unspecified type, uncontrolled	 DMII renal uncntrld"})
Diagnosis.create!({ idc9: "25043", name:	"Diabetes with renal manifestations, type I [juvenile type], uncontrolled	 DMI renal uncntrld"})
Diagnosis.create!({ idc9: "25050", name:	"Diabetes with ophthalmic manifestations, type II or unspecified type, not stated as uncontrolled	 DMII ophth nt st uncntrl"})
Diagnosis.create!({ idc9: "25051", name:	"Diabetes with ophthalmic manifestations, type I [juvenile type], not stated as uncontrolled	 DMI ophth nt st uncntrld"})
Diagnosis.create!({ idc9: "25052", name:	"Diabetes with ophthalmic manifestations, type II or unspecified type, uncontrolled	 DMII ophth uncntrld"})
Diagnosis.create!({ idc9: "25053", name:	"Diabetes with ophthalmic manifestations, type I [juvenile type], uncontrolled	 DMI ophth uncntrld"})
Diagnosis.create!({ idc9: "25060", name:	"Diabetes with neurological manifestations, type II or unspecified type, not stated as uncontrolled	 DMII neuro nt st uncntrl"})
Diagnosis.create!({ idc9: "25061", name:	"Diabetes with neurological manifestations, type I [juvenile type], not stated as uncontrolled	 DMI neuro nt st uncntrld"})
Diagnosis.create!({ idc9: "25062", name:	"Diabetes with neurological manifestations, type II or unspecified type, uncontrolled	 DMII neuro uncntrld"})
Diagnosis.create!({ idc9: "25063", name:	"Diabetes with neurological manifestations, type I [juvenile type], uncontrolled	 DMI neuro uncntrld"})
Diagnosis.create!({ idc9: "25070", name:	"Diabetes with peripheral circulatory disorders, type II or unspecified type, not stated as uncontrolled	 DMII circ nt st uncntrld"})
Diagnosis.create!({ idc9: "25071", name:	"Diabetes with peripheral circulatory disorders, type I [juvenile type], not stated as uncontrolled	 DMI circ nt st uncntrld"})
Diagnosis.create!({ idc9: "25072", name:	"Diabetes with peripheral circulatory disorders, type II or unspecified type, uncontrolled	 DMII circ uncntrld"})
Diagnosis.create!({ idc9: "25073", name:	"Diabetes with peripheral circulatory disorders, type I [juvenile type], uncontrolled	 DMI circ uncntrld"})
Diagnosis.create!({ idc9: "25080", name:	"Diabetes with other specified manifestations, type II or unspecified type, not stated as uncontrolled	 DMII oth nt st uncntrld"})
Diagnosis.create!({ idc9: "25081", name:	"Diabetes with other specified manifestations, type I [juvenile type], not stated as uncontrolled	 DMI oth nt st uncntrld"})
Diagnosis.create!({ idc9: "25082", name:	"Diabetes with other specified manifestations, type II or unspecified type, uncontrolled	 DMII oth uncntrld"})
Diagnosis.create!({ idc9: "25083", name:	"Diabetes with other specified manifestations, type I [juvenile type], uncontrolled	 DMI oth uncntrld"})
Diagnosis.create!({ idc9: "25090", name:	"Diabetes with unspecified complication, type II or unspecified type, not stated as uncontrolled	 DMII unspf nt st uncntrl"})
Diagnosis.create!({ idc9: "25091", name:	"Diabetes with unspecified complication, type I [juvenile type], not stated as uncontrolled	 DMI unspf nt st uncntrld"})
Diagnosis.create!({ idc9: "25092", name:	"Diabetes with unspecified complication, type II or unspecified type, uncontrolled	 DMII unspf uncntrld"})
Diagnosis.create!({ idc9: "25093", name:	"Diabetes with unspecified complication, type I [juvenile type], uncontrolled"})
Diagnosis.create!({ idc9: "2535", name: "Diabetes insipidus"})
Diagnosis.create!({ idc9: "36641", name:	"Diabetic cataract"})
Diagnosis.create!({ idc9: "36201", name:	"Background diabetic retinopathy	 Diabetic retinopathy NOS"})
Diagnosis.create!({ idc9: "36202", name:	"Proliferative diabetic retinopathy	 Prolif diab retinopathy"})
Diagnosis.create!({ idc9: "36203", name:	"Nonproliferative diabetic retinopathy NOS	 Nonprolf db retnoph NOS"})
Diagnosis.create!({ idc9: "36204", name:	"Mild nonproliferative diabetic retinopathy	 Mild nonprolf db retnoph"})
Diagnosis.create!({ idc9: "36205", name:	"Moderate nonproliferative diabetic retinopathy	 Mod nonprolf db retinoph"})
Diagnosis.create!({ idc9: "36206", name:	"Severe nonproliferative diabetic retinopathy	 Sev nonprolf db retinoph"})
Diagnosis.create!({ idc9: "36207", name:	"Diabetic macular edema"})
Diagnosis.create!({ idc9: "5881", name: "Nephrogenic diabetes insipidus"})
Diagnosis.create!({ idc9: "64800", name:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, unspecified as to episode of care or not applicable	 Diabetes in preg-unspec"})
Diagnosis.create!({ idc9: "64801", name:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, delivered, with or without mention of antepartum condition	 Diabetes-delivered"})
Diagnosis.create!({ idc9: "64802", name:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, delivered, with mention of postpartum complication	 Diabetes-delivered w p/p"})
Diagnosis.create!({ idc9: "64803", name:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, antepartum condition or complication	 Diabetes-antepartum"})
Diagnosis.create!({ idc9: "64804", name:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, postpartum condition or complication"})
Diagnosis.create!({ idc9: "9623", name: "Poisoning by insulins and antidiabetic agents"})
Diagnosis.create!({ idc9: "V1221", name:	"Personal history of gestational diabetes"})