development:
  adapter: postgresql
  database: preventIT_dev
  host: localhost
  username: Doug
  password: ENV['DOUG_PW']
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: preventIT_test
  host: localhost
  username: Doug
  password: ENV['DOUG_PW']
