Diagnosis.create!({ code: "24900", description:	"Secondary diabetes mellitus without mention of complication, not stated as uncontrolled, or unspecified	 Sec DM wo cmp nt st uncn"})
Diagnosis.create!({ code: "24901", description:	"Secondary diabetes mellitus without mention of complication, uncontrolled	 Sec DM wo comp uncontrld"})
Diagnosis.create!({ code: "24910", description:	"Secondary diabetes mellitus with ketoacidosis, not stated as uncontrolled, or unspecified	 Sec DM keto nt st uncntr"})
Diagnosis.create!({ code: "24911", description:	"Secondary diabetes mellitus with ketoacidosis, uncontrolled	 Sec DM ketoacd uncntrld"})
Diagnosis.create!({ code: "24920", description:	"Secondary diabetes mellitus with hyperosmolarity, not stated as uncontrolled, or unspecified	 Sec DM hpros nt st uncnr"})
Diagnosis.create!({ code: "24921", description:	"Secondary diabetes mellitus with hyperosmolarity, uncontrolled	 Sec DM hprosmlr uncntrld"})
Diagnosis.create!({ code: "24930", description:	"Secondary diabetes mellitus with other coma, not stated as uncontrolled, or unspecified	 Sec DM ot cma nt st uncn"})
Diagnosis.create!({ code: "24931", description:	"Secondary diabetes mellitus with other coma, uncontrolled	 Sec DM oth coma uncntrld"})
Diagnosis.create!({ code: "24940", description:	"Secondary diabetes mellitus with renal manifestations, not stated as uncontrolled, or unspecified	 Sec DM renl nt st uncntr"})
Diagnosis.create!({ code: "24941", description:	"Secondary diabetes mellitus with renal manifestations, uncontrolled	 Sec DM renal uncontrld"})
Diagnosis.create!({ code: "24950", description:	"Secondary diabetes mellitus with ophthalmic manifestations, not stated as uncontrolled, or unspecified	 Sec DM ophth nt st uncn"})
Diagnosis.create!({ code: "24951", description:	"Secondary diabetes mellitus with ophthalmic manifestations, uncontrolledcode	 Sec DM ophth uncontrld"})
Diagnosis.create!({ code: "24960", description:	"Secondary diabetes mellitus with neurological manifestations, not stated as uncontrolled, or unspecified	 Sec DM neuro nt st uncn"})
Diagnosis.create!({ code: "24961", description:	"Secondary diabetes mellitus with neurological manifestations, uncontrolled	 Sec DM neuro uncontrld"})
Diagnosis.create!({ code: "24970", description:	"Secondary diabetes mellitus with peripheral circulatory disorders, not stated as uncontrolled, or unspecified	 Sec DM circ nt st uncntr"})
Diagnosis.create!({ code: "24971", description:	"Secondary diabetes mellitus with peripheral circulatory disorders, uncontrolled	 Sec DM circ uncontrld"})
Diagnosis.create!({ code: "24980", description:	"Secondary diabetes mellitus with other specified manifestations, not stated as uncontrolled, or unspecified	 Sec DM oth nt st uncontr"})
Diagnosis.create!({ code: "24981", description:	"Secondary diabetes mellitus with other specified manifestations, uncontrolled	 Sec DM other uncontrld"})
Diagnosis.create!({ code: "24990", description:	"Secondary diabetes mellitus with unspecified complication, not stated as uncontrolled, or unspecified	 Sec DM unsp nt st uncon"})
Diagnosis.create!({ code: "24991", description:	"Secondary diabetes mellitus with unspecified complication, uncontrolled	 Sec DM unsp uncontrold"})
Diagnosis.create!({ code: "25000", description:	"Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled	 DMII wo cmp nt st uncntr"})
Diagnosis.create!({ code: "25001", description:	"Diabetes mellitus without mention of complication, type I [juvenile type], not stated as uncontrolled	 DMI wo cmp nt st uncntrl"})
Diagnosis.create!({ code: "25002", description:	"Diabetes mellitus without mention of complication, type II or unspecified type, uncontrolled	 DMII wo cmp uncntrld"})
Diagnosis.create!({ code: "25003", description:	"Diabetes mellitus without mention of complication, type I [juvenile type], uncontrolled	 DMI wo cmp uncntrld"})
Diagnosis.create!({ code: "25010", description:	"Diabetes with ketoacidosis, type II or unspecified type, not stated as uncontrolled	 DMII keto nt st uncntrld"})
Diagnosis.create!({ code: "25011", description:	"Diabetes with ketoacidosis, type I [juvenile type], not stated as uncontrolled	 DMI keto nt st uncntrld"})
Diagnosis.create!({ code: "25012", description:	"Diabetes with ketoacidosis, type II or unspecified type, uncontrolled	 DMII ketoacd uncontrold"})
Diagnosis.create!({ code: "25013", description:	"Diabetes with ketoacidosis, type I [juvenile type], uncontrolled	 DMI ketoacd uncontrold"})
Diagnosis.create!({ code: "25020", description:	"Diabetes with hyperosmolarity, type II or unspecified type, not stated as uncontrolled	 DMII hprsm nt st uncntrl"})
Diagnosis.create!({ code: "25021", description:	"Diabetes with hyperosmolarity, type I [juvenile type], not stated as uncontrolled	 DMI hprsm nt st uncntrld"})
Diagnosis.create!({ code: "25022", description:	"Diabetes with hyperosmolarity, type II or unspecified type, uncontrolled	 DMII hprosmlr uncontrold"})
Diagnosis.create!({ code: "25023", description:	"Diabetes with hyperosmolarity, type I [juvenile type], uncontrolled	 DMI hprosmlr uncontrold"})
Diagnosis.create!({ code: "25030", description:	"Diabetes with other coma, type II or unspecified type, not stated as uncontrolled	 DMII o cm nt st uncntrld"})
Diagnosis.create!({ code: "25031", description:	"Diabetes with other coma, type I [juvenile type], not stated as uncontrolled	 DMI o cm nt st uncntrld"})
Diagnosis.create!({ code: "25032", description:	"Diabetes with other coma, type II or unspecified type, uncontrolled	 DMII oth coma uncontrold"})
Diagnosis.create!({ code: "25033", description:	"Diabetes with other coma, type I [juvenile type], uncontrolled	 DMI oth coma uncontrold"})
Diagnosis.create!({ code: "25040", description:	"Diabetes with renal manifestations, type II or unspecified type, not stated as uncontrolled	 DMII renl nt st uncntrld"})
Diagnosis.create!({ code: "25041", description:	"Diabetes with renal manifestations, type I [juvenile type], not stated as uncontrolled	 DMI renl nt st uncntrld"})
Diagnosis.create!({ code: "25042", description:	"Diabetes with renal manifestations, type II or unspecified type, uncontrolled	 DMII renal uncntrld"})
Diagnosis.create!({ code: "25043", description:	"Diabetes with renal manifestations, type I [juvenile type], uncontrolled	 DMI renal uncntrld"})
Diagnosis.create!({ code: "25050", description:	"Diabetes with ophthalmic manifestations, type II or unspecified type, not stated as uncontrolled	 DMII ophth nt st uncntrl"})
Diagnosis.create!({ code: "25051", description:	"Diabetes with ophthalmic manifestations, type I [juvenile type], not stated as uncontrolled	 DMI ophth nt st uncntrld"})
Diagnosis.create!({ code: "25052", description:	"Diabetes with ophthalmic manifestations, type II or unspecified type, uncontrolled	 DMII ophth uncntrld"})
Diagnosis.create!({ code: "25053", description:	"Diabetes with ophthalmic manifestations, type I [juvenile type], uncontrolled	 DMI ophth uncntrld"})
Diagnosis.create!({ code: "25060", description:	"Diabetes with neurological manifestations, type II or unspecified type, not stated as uncontrolled	 DMII neuro nt st uncntrl"})
Diagnosis.create!({ code: "25061", description:	"Diabetes with neurological manifestations, type I [juvenile type], not stated as uncontrolled	 DMI neuro nt st uncntrld"})
Diagnosis.create!({ code: "25062", description:	"Diabetes with neurological manifestations, type II or unspecified type, uncontrolled	 DMII neuro uncntrld"})
Diagnosis.create!({ code: "25063", description:	"Diabetes with neurological manifestations, type I [juvenile type], uncontrolled	 DMI neuro uncntrld"})
Diagnosis.create!({ code: "25070", description:	"Diabetes with peripheral circulatory disorders, type II or unspecified type, not stated as uncontrolled	 DMII circ nt st uncntrld"})
Diagnosis.create!({ code: "25071", description:	"Diabetes with peripheral circulatory disorders, type I [juvenile type], not stated as uncontrolled	 DMI circ nt st uncntrld"})
Diagnosis.create!({ code: "25072", description:	"Diabetes with peripheral circulatory disorders, type II or unspecified type, uncontrolled	 DMII circ uncntrld"})
Diagnosis.create!({ code: "25073", description:	"Diabetes with peripheral circulatory disorders, type I [juvenile type], uncontrolled	 DMI circ uncntrld"})
Diagnosis.create!({ code: "25080", description:	"Diabetes with other specified manifestations, type II or unspecified type, not stated as uncontrolled	 DMII oth nt st uncntrld"})
Diagnosis.create!({ code: "25081", description:	"Diabetes with other specified manifestations, type I [juvenile type], not stated as uncontrolled	 DMI oth nt st uncntrld"})
Diagnosis.create!({ code: "25082", description:	"Diabetes with other specified manifestations, type II or unspecified type, uncontrolled	 DMII oth uncntrld"})
Diagnosis.create!({ code: "25083", description:	"Diabetes with other specified manifestations, type I [juvenile type], uncontrolled	 DMI oth uncntrld"})
Diagnosis.create!({ code: "25090", description:	"Diabetes with unspecified complication, type II or unspecified type, not stated as uncontrolled	 DMII unspf nt st uncntrl"})
Diagnosis.create!({ code: "25091", description:	"Diabetes with unspecified complication, type I [juvenile type], not stated as uncontrolled	 DMI unspf nt st uncntrld"})
Diagnosis.create!({ code: "25092", description:	"Diabetes with unspecified complication, type II or unspecified type, uncontrolled	 DMII unspf uncntrld"})
Diagnosis.create!({ code: "25093", description:	"Diabetes with unspecified complication, type I [juvenile type], uncontrolled"})
Diagnosis.create!({ code: "2535", description: "Diabetes insipidus"})
Diagnosis.create!({ code: "36641", description:	"Diabetic cataract"})
Diagnosis.create!({ code: "36201", description:	"Background diabetic retinopathy	 Diabetic retinopathy NOS"})
Diagnosis.create!({ code: "36202", description:	"Proliferative diabetic retinopathy	 Prolif diab retinopathy"})
Diagnosis.create!({ code: "36203", description:	"Nonproliferative diabetic retinopathy NOS	 Nonprolf db retnoph NOS"})
Diagnosis.create!({ code: "36204", description:	"Mild nonproliferative diabetic retinopathy	 Mild nonprolf db retnoph"})
Diagnosis.create!({ code: "36205", description:	"Moderate nonproliferative diabetic retinopathy	 Mod nonprolf db retinoph"})
Diagnosis.create!({ code: "36206", description:	"Severe nonproliferative diabetic retinopathy	 Sev nonprolf db retinoph"})
Diagnosis.create!({ code: "36207", description:	"Diabetic macular edema"})
Diagnosis.create!({ code: "5881", description: "Nephrogenic diabetes insipidus"})
Diagnosis.create!({ code: "64800", description:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, unspecified as to episode of care or not applicable	 Diabetes in preg-unspec"})
Diagnosis.create!({ code: "64801", description:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, delivered, with or without mention of antepartum condition	 Diabetes-delivered"})
Diagnosis.create!({ code: "64802", description:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, delivered, with mention of postpartum complication	 Diabetes-delivered w p/p"})
Diagnosis.create!({ code: "64803", description:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, antepartum condition or complication	 Diabetes-antepartum"})
Diagnosis.create!({ code: "64804", description:	"Diabetes mellitus of mother, complicating pregnancy, childbirth, or the puerperium, postpartum condition or complication"})
Diagnosis.create!({ code: "9623", description: "Poisoning by insulins and antidiabetic agents"})
Diagnosis.create!({ code: "V1221", description:	"Personal history of gestational diabetes"})